### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hisham2007** [cullaboration/userhook-sdk-android#3] opened 2016-12-02 23:34 UTC
I used this code which uses Arabic language but unfortunately, message displayed with strange letters :
` UserHook.showFeedbackPrompt("يوجد رد من المطور على رسالتك التي ارسلتها سابقا. هل تريد قراءة الرد الآن؟", "لاحقا", "اقرأ الآن");
`

**Comment by hisham2007** [comment] 2016-12-02 23:38
Also I found a new issue, when I force RTL. when use

 ` UserHook.showFeedbackPrompt("You have a new response to your recently submitted feedback. Do you want to read it now?", "Read Now", "Later");`


the read later button acts as Read now and vice versa.


I use this code to force rtl:

`   try {
            String languageToLoad = "ar"; // your language
            Locale locale = new Locale(languageToLoad);
            Locale.setDefault(locale);
            Configuration config = activity.getResources().getConfiguration();
            //config.locale = locale;
            config.setLocale(locale);
            activity.getResources().updateConfiguration(config,
                    activity.getResources().getDisplayMetrics());
            activity.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        } catch (Exception ex){
            LogUtil.e(ex);
        }`

**Comment by whynotmatt** [comment] 2016-12-05 16:25
The encoding issue should be fixed with commit https://github.com/cullaboration/userhook-sdk-android/commit/adb829144a7714c914e3289a46dbd0b75c4a22ec

I am not able to reproduce the issue where the button actions are getting reversed. Even if the language is RTL, the left button will be considered the "Positive" button and the right button will be the "Negative" button for a showFeedbackPrompt() call.

**Comment by hisham2007** [comment] 2016-12-05 22:48
please call the code i mentioned above before super.oncreate() to force RTL PROGRAMATICALLY

**Closed** 2017-03-27 15:49 UTC
